name: CI/CD Pipeline

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - main
      - alpha
      - beta
      - canary
      - pre/rc

jobs:
  lint:
    uses: kurocado-studio/dev-ops/.github/workflows/workflow.lint.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    uses: kurocado-studio/dev-ops/.github/workflows/workflow.release.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    with:
      branch_name: ${{ github.ref_name }}
